name: "CI - Test Features"
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features:
          - bats
        baseImage:
          - debian:latest
          - ubuntu:latest
          - alpine:latest
          - rockylinux:9
          - mcr.microsoft.com/devcontainers/base:ubuntu
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1

      - name: "Install requirements"
        run: just install-dev-requirements

      - name: "Test install script ${{ matrix.features }}"
        run: just test-installing ${{ matrix.features }}

      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: just test ${{ matrix.features }} ${{ matrix.baseImage }}

  test-global:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Testing global scenarios"
        run: devcontainer features test --global-scenarios-only .
